AllCops:
  NewCops: enable

Style/FormatString:
  Enabled: true
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 90

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
