AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Style/FormatString:
  Enabled: true
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Layout/LineLength:
  Max: 90

Metrics/BlockLength:
  Exclude:
    - '*/schema.rb'
    - 'oughta.gemspec'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
