name: Commit checks

on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: &ruby-matrix
      matrix:
        ruby-version: [3.0.x, 2.7.x, 2.6.x, 2.5.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby-version }}

    - name: Run the default task
      run: |
        gem install bundler -v 2.2.4
        bundle install
        bundle exec rspec spec

  lint:
    runs-on: ubuntu-latest
    strategy:
      <<: *ruby-matrix

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.4
        bundle install
        bundle exec rubocop
